apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine-container
        image: alpine:latest
        command: ["/bin/sh"]
        args: ["-c", "sleep 3600"]  # Exemple de commande pour garder le conteneur en cours d'exécution
---
apiVersion: v1
kind: Service
metadata:
  name: alpine-service
spec:
  selector:
    app: alpine
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
