name: kubernetes Deployment

on:
  pull_request:
    branches: [main]
jobs:
  deploy:
    run-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup kubeconfig
      run : |
        echo "${{secrets.KUBECONFIG}}" | base64 --decode > kubeconfig
    - name: Apply kubernets configurations
      run: |
        export KUBECONFIG=kubeconfig
        kubectl apply -n saas-health -f k8s